name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  setup:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        run: |
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          
          # Import certificate
          echo $BUILD_CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          
          # Allow codesign to access keychain
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build App
        env:
          TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          xcodebuild clean archive \
            -project MultiScreenCapturer.xcodeproj \
            -scheme MultiScreenCapturer \
            -configuration Release \
            -archivePath ./build/MultiScreenCapturer.xcarchive \
            DEVELOPMENT_TEAM=$TEAM_ID \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Development"

      - name: Create App Bundle
        run: |
          mkdir -p ./artifacts
          cp -r ./build/MultiScreenCapturer.xcarchive/Products/Applications/MultiScreenCapturer.app ./artifacts/
          cd artifacts
          zip -r ../MultiScreenCapturer-${{ needs.setup.outputs.version }}-macos.zip .
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: MultiScreenCapturer-${{ needs.setup.outputs.version }}-macos.zip
          draft: false
          prerelease: false
          generate_release_notes: true
