name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build App
        run: |
          xcodebuild clean archive \
            -project MultiScreenCapturer.xcodeproj \
            -scheme MultiScreenCapturer \
            -configuration Release \
            -archivePath ./build/MultiScreenCapturer.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create App Bundle
        run: |
          mkdir -p ./artifacts
          cp -r ./build/MultiScreenCapturer.xcarchive/Products/Applications/MultiScreenCapturer.app ./artifacts/
          cd artifacts
          zip -r ../MultiScreenCapturer-${{ needs.setup.outputs.version }}-macos.zip .
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: MultiScreenCapturer-${{ needs.setup.outputs.version }}-macos.zip
          draft: false
          prerelease: false
          generate_release_notes: true